import Head from 'next/head'
import Logo from '../images/Logo.png'
import Image from 'next/image'
import Manos from '../images/manos.jpg'
import styles2 from '@/styles/CrearUsuario.module.css'
import { useState } from 'react'
import axios from 'axios';
import { useRouter } from 'next/router';

/*
CREATE TABLE clients (
    client_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    phone VARCHAR(255) NOT NULL,
    inscription_date DATE NOT NULL,
    emergency_contact VARCHAR(255) NOT NULL,
    emergency_phone VARCHAR(255) NOT NULL,
    rate_id INT,
    available_classes INT
  );
*/ 

export default function CrearUsuarioInfo(){
    const router = useRouter();
    const { employee_id } = router.query;
    const initialFormData = {
        name: '',
        surname: '',
        email: '',
        birthdate: '',
        inscription_date: '',
        phone: '',
        emergency_contact: '',
        emergency_phone: '',
        rate_id: '',
        password: '',
        password2: '',
        available_classes: 10
    }
    const [formData, setFormData] = useState({
        name: '',
        surname: '',
        email: '',
        birthdate: '',
        inscription_date: '',
        phone: '',
        emergency_contact: '',
        emergency_phone: '',
        rate_id: '',
        password: '',
        password2: '',
        available_classes: 10
    });

    const handleEvent = (e) => {
        const currentDate = new Date().toISOString().split('T')[0];
        setFormData({
            ...formData,
            [e.target.name]: e.target.value,
            inscription_date: currentDate
        });
        //setFormData({ ...formData, inscription_date: currentDate });
    }

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('http://localhost:8000/clients', formData);
            console.log(response.data); // Assuming the API returns the created client data
            setFormData(initialFormData);
          } catch (error) {
            console.error(error);
        }
        
        setFormData(initialFormData)
        router.push(`/paginaMonitor?employee_id=${employee_id}`)
    }
    
    const handleSubmit2 = async (e) => {
        console.log(formData)
        e.preventDefault();
    }
    const passwordMatch = formData.password === formData.password2;

    return (
        <>
            <Head>
                <title>Crear Usuario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles2.backgroundContainer}>
                <Image src={Manos} alt="manos" className={styles2.imagenFondo} />
                <div className={styles2.backgroundCanvas}>
                    <div className={styles2.propContainer}>
                        <h2 className={styles2.formTitle}>Datos de Usuario</h2>
                        <form className={styles2.formContainer} onSubmit={handleSubmit}>

                            <div className={styles2.formContainerInfo}>

                                <input
                                    className={styles2.formInput} 
                                    name='name'
                                    type="text" 
                                    placeholder='Nombre' 
                                    value={formData.name}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input
                                    className={styles2.formInput}
                                    name='surname'
                                    type="text"
                                    placeholder='Apellidos'
                                    value={formData.surname}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input
                                    className={styles2.formInput} 
                                    name='email'
                                    type="text" 
                                    placeholder='Email' 
                                    value={formData.email}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='birthdate'
                                    type="text" 
                                    placeholder='Fecha de Nacimiento' 
                                    value={formData.birthdate}
                                    onChange={handleEvent}
                                    required 
                                    pattern='^(19|20)\d\d-(0[1-9]|1[0-2])-(0[1-9]|1[0-9]|2[0-9]|3[01])$'
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='phone'
                                    type="text" 
                                    placeholder='Teléfono' 
                                    value={formData.phone}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='emergency_contact'
                                    type="text" 
                                    placeholder='Contacto de Emergencia' 
                                    value={formData.emergency_contact}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='emergency_phone'
                                    type="text" 
                                    placeholder='Teléfono de Emergencia' 
                                    value={formData.emergency_phone}
                                    onChange={handleEvent}
                                    required 
                                />
                                <input 
                                    className={styles2.formInput} 
                                    name='rate_id'
                                    type="text" 
                                    placeholder='Tarifa' 
                                    value={formData.rate_id}
                                    onChange={handleEvent}
                                    required 
                                />
                            </div>
                            <div className={styles2.passwordContainer}>
                                <input 
                                    className={styles2.formInput} 
                                    name="password"
                                    type="password" 
                                    placeholder='Contraseña'
                                    value={formData.password}
                                    onChange={handleEvent}
                                    required 
                                />
                                <input 
                                    className={styles2.formInput} 
                                    name="password2"
                                    type="password" 
                                    placeholder='Repetir contraseña' 
                                    value={formData.password2}
                                    onChange={handleEvent}
                                    required 
                                />
                            </div>
                            <button 
                                className={styles2.redRoundButton} 
                                type="submit" 
                                disabled={!passwordMatch}
                            >Crear Usuario
                            </button>
                        </form>
                    </div>
                </div>
            </div>


        </>
    )
}

