import Head from 'next/head'
import Logo from '../images/Logo.png'
import Image from 'next/image'
import Manos from '../images/manos.jpg'
import styles2 from '@/styles/CrearUsuario.module.css'
import { useState } from 'react'

export default function CrearUsuarioInfo(){
    const patologias = ['Ninguna', 'Diabetes', 'Cardiovascular', 'Asma', 'Obesidad', 'Otra'];
    const initialFormData = {
        nombre: '',
        apellidos: '',
        email: '',
        fechaNacimiento: '',
        telefono: '',
        telefonoEmergencia: '',
        patologia: '',
        descripcionPatologia: '',
        contrasena: '',
        contrasena2: ''
    }
    const [formData, setFormData] = useState({
        nombre: '',
        apellidos: '',
        email: '',
        fechaNacimiento: '',
        telefono: '',
        telefonoEmergencia: '',
        patologia: '',
        descripcionPatologia: '',
        contrasena: '',
        contrasena2: ''
    });

    const handleEvent = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    }

    const handleSubmit = (e) => {
        e.preventDefault();
        console.log(formData);
        setFormData(initialFormData)
    }
    
    const passwordMatch = formData.contrasena === formData.contrasena2;

    return (
        <>
            <Head>
                <title>Crear Usuario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles2.backgroundContainer}>
                <Image src={Manos} alt="manos" className={styles2.imagenFondo} />
                <div className={styles2.backgroundCanvas}>
                    <div className={styles2.propContainer}>
                        <h2 className={styles2.formTitle}>Datos de Usuario</h2>
                        <form className={styles2.formContainer} onSubmit={handleSubmit}>

                            <div className={styles2.formContainerInfo}>

                                <input
                                    className={styles2.formInput} 
                                    name='nombre'
                                    type="text" 
                                    placeholder='Nombre' 
                                    value={formData.nombre}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input
                                    className={styles2.formInput}
                                    name='apellidos'
                                    type="text"
                                    placeholder='Apellidos'
                                    value={formData.apellidos}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input
                                    className={styles2.formInput} 
                                    name='email'
                                    type="text" 
                                    placeholder='Email' 
                                    value={formData.email}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='fechaNacimiento'
                                    type="text" 
                                    placeholder='Fecha de Nacimiento' 
                                    value={formData.fechaNacimiento}
                                    onChange={handleEvent}
                                    required 
                                    pattern='^(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[0-2])/(19|20)\d\d$'
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='telefono'
                                    type="text" 
                                    placeholder='Teléfono' 
                                    value={formData.telefono}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='telefonoEmergencia'
                                    type="text" 
                                    placeholder='Teléfono de Emergencia' 
                                    value={formData.telefonoEmergencia}
                                    onChange={handleEvent}
                                    required 
                                />

                                <input 
                                    className={styles2.formInput} 
                                    name='patologia'
                                    list='options' 
                                    placeholder='Patología' 
                                    value={formData.patologia}
                                    onChange={handleEvent}
                                    required 
                                />

                                <datalist id='options'>
                                    {patologias.map((patologia, index) => (
                                        <option key={index} value={patologia} />
                                    ))}
                                </datalist>

                                <input 
                                    className={styles2.formInput} 
                                    name='descripcionPatologia'
                                    type="text" 
                                    placeholder='Descripción Patología' 
                                    value={formData.descripcionPatologia}
                                    onChange={handleEvent}
                                />
                            </div>
                            <div className={styles2.passwordContainer}>
                                <input 
                                    className={styles2.formInput} 
                                    name="contrasena"
                                    type="password" 
                                    placeholder='Contraseña'
                                    value={formData.contrasena}
                                    onChange={handleEvent}
                                    required 
                                />
                                <input 
                                    className={styles2.formInput} 
                                    name="contrasena2"
                                    type="password" 
                                    placeholder='Repetir contraseña' 
                                    value={formData.contrasena2}
                                    onChange={handleEvent}
                                    required 
                                />
                            </div>
                            <button 
                                className={styles2.redRoundButton} 
                                type="submit" 
                                disabled={!passwordMatch}
                            >Crear Usuario
                            </button>
                        </form>
                    </div>
                </div>
            </div>


        </>
    )
}

