import Head from 'next/head'
import Logo from '../images/Logo.png'
import Image from 'next/image'
import Manos from '../images/manos.jpg'
import Instalaciones2 from '../images/Instalaciones2.jpg'
import Instalaciones3 from '../images/Instalaciones3.jpg'
import Instalaciones4 from '../images/Instalaciones4.jpg'
import Instalaciones6 from '../images/Instalaciones6.jpg'
import Instalaciones7 from '../images/Instalaciones7.jpg'
import Img1 from '../images/55KG.jpg'
import Icon1 from '../images/atpersonalizadared.png'
import Icon2 from '../images/calendar-week.svg'
import Icon3 from '../images/applered.png'
import Icon4 from '../images/geo-alt-fill.svg'
import Icon5 from '../images/telephone-fill.svg'
import Icon6 from '../images/envelope.svg'
import Icon7 from '../images/instagram.svg'
import Icon8 from '../images/facebook.svg'
import Icon9 from '../images/twitter.svg'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import styles2 from '@/styles/CrearUsuario.module.css'

export default function CrearUsuarioInfo(){
    const patologias = ['Ninguna', 'Diabetes', 'Cardiovascular', 'Asma', 'Obesidad', 'Otra'];
    return (
        <>

            <Head>
                <title>Crear Usuario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles2.backgroundContainer}>
                <Image src={Manos} alt="manos" className={styles2.imagenFondo} />
                <div className={styles2.backgroundCanvas}>
                    <div className={styles2.propContainer}>
                        <h2 className={styles2.formTitle}>Datos de Usuario</h2>
                        <div className={styles2.formContainer}>
                            <input className={styles2.formInput} type="text" placeholder='Nombre' required />
                            <input className={styles2.formInput} type="text" placeholder='Apellidos' required />
                            <input className={styles2.formInput} type="text" placeholder='Email' required />
                            <input className={styles2.formInput} type="text" placeholder='Fecha de Nacimiento' required pattern='^(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[0-2])/(19|20)\d\d$'/>
                            <input className={styles2.formInput} type="text" placeholder='Teléfono' required />
                            <input className={styles2.formInput} type="text" placeholder='Teléfono de Emergencia' required />
                            <input className={styles2.formInput} list='options' placeholder='Patología' required />
                            <datalist id='options'>
                                {patologias.map((patologia, index) => (
                                    <option key={index} value={patologia} />
                                ))}
                            </datalist>
                            <input className={styles2.formInput} type="text" placeholder='Descripción Patología' />
                        </div>
                        <div className={styles2.passwordContainer}>
                            <input className={styles2.formInput} type="password" placeholder='Contraseña' required />
                            <input className={styles2.formInput} type="password" placeholder='Repetir contraseña' required />
                        </div>
                        <button className={styles2.redRoundButton}>Crear Usuario</button>
                    </div>
                </div>
            </div>


        </>
    )
}

