import Head from 'next/head'
import Logo from '../images/Logo.png'
import Image from 'next/image'
import Instalaciones2 from '../images/Instalaciones2.jpg'
import Instalaciones3 from '../images/Instalaciones3.jpg'
import Instalaciones4 from '../images/Instalaciones4.jpg'
import Instalaciones6 from '../images/Instalaciones6.jpg'
import Instalaciones7 from '../images/Instalaciones7.jpg'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Crossfit G3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className={styles.flex}>
        <Image src={Logo} alt="logo" width={100}/>
        <nav className={styles.nav}>
          <ul>
            <li> <a href="#top"> Inicio </a> </li>
            <li> <a href="#top"> Nosotros </a> </li>
            <li> <a href="#top"> Galería </a> </li>
            <li> <a href="#top"> Horarios </a> </li>
            <li> <a href="#top"> Tarifas </a> </li>
            <li> <a href="#top"> Contacto </a> </li>
          </ul>
        </nav>
      <br/>
    </header>

      <main className={styles.main}>
        <div className={styles.part1}>
          <div>
            SE TU MEJOR VERSIÓN
          </div>
          <div>
            G3 CROSSFIT
          </div>
          <div>
            INICIA HOY
          </div>        
        </div>

      <div className={styles.part2}>
        <div className={styles.container2}>
          <div>
            <b>Bienvenido a G3 Crossfit</b>
          </div>
          <div style={{ borderBottom: '1px solid red' }}></div>
          <div>
          En nuestro box, nos enfocamos en un entrenamiento intenso y desafiante, 
          pero también en crear una comunidad que apoye y motive a sus miembros a 
          alcanzar sus objetivos de fitness. Nuestros entrenadores están altamente 
          capacitados para guiarlo y ayudarlo a mejorar su técnica, prevenir lesiones 
          y aumentar su fuerza y resistencia. Valoramos la seguridad y el progreso sostenible,
          por lo que nos aseguramos de adaptar los entrenamientos a las necesidades y capacidades individuales de cada miembro. 
          </div>
        </div>

        <div className={styles.container2}>
          <Image src={Instalaciones2} alt="inst2" width={300}/>
        </div>

      </div>

      <div className={styles.part3}>
        <div className= {styles.inst}>
          <div className= {styles.rtb}>
            <Image src={Logo} alt="logo" width={100}/>
            <div> Atención Personalizada </div>
          </div>
          <div className= {styles.rtb}>
            <Image src={Logo} alt="logo" width={100}/>
            <div> Entrenamientos nuevos cada día </div>
          </div>
          <div className= {styles.rtb}>
            <Image src={Logo} alt="logo" width={100}/>
            <div> Soporte de nutrición </div>
          </div>
        </div>
        <div className= {styles.inst2}>
          <div> CONOCE NUESTRAS </div>
          <div style={{ borderBottom: '1px solid red' }}></div>
          <div> Instalaciones </div>
        </div>
        <div className= {styles.inst}>
          <Image src={Instalaciones2} alt="inst2" width={300}/>
          <Image src={Instalaciones3} alt="inst3" width={300}/>
          <Image src={Instalaciones4} alt="inst4" width={300}/>
          <Image src={Instalaciones6} alt="inst6" width={300}/>
          <Image src={Instalaciones7} alt="inst7" width={300}/>
        </div>

      </div>

      <div className={styles.part4}>
        <button>Conoce nuestros horarios</button>
        <div>TARIFAS</div>
        <div className={styles.tarifas}>
          <div className={styles.card}>
            <div>Crossfit ilimitado 1 mes</div>
            <div>95€</div>
            <div>Paga tu cuota cada mes</div>
          </div>

          <div className={styles.card}>
            <div>Crossfit ilimitado 6 meses</div>
            <div>535€</div>
            <div>6% de descuento</div>
          </div>

          <div className={styles.card}>
            <div>Crossfit ilimitado 12 meses</div>
            <div>995€</div>
            <div>12% de descuento</div>
          </div>
        </div>
      </div>
  
      <div className={styles.part5}>
        <div>MADRID</div>
        <div>
          <div className={styles.datos}>
            <Image src={Logo} alt="logo" width={100}/>
            <p> Calle Dos Amigos, 3 28015 MADRID</p>
          </div>
          <div className={styles.datos}>
            <Image src={Logo} alt="logo" width={100}/>
            <p>644885452</p>
          </div>
          <div className={styles.datos}>
            <Image src={Logo} alt="logo" width={100}/>
            <p>crossfitg3@gmail.com</p>
          </div>
        </div>

      </div>  
      
      <footer>
        <div>        
          <Image src={Logo} alt="instagram" width={100}/>
          <Image src={Logo} alt="twitter" width={100}/>
          <Image src={Logo} alt="facebook" width={100}/>
        </div>

        <div>
          CROSSFIT G3 - TODOS LOS DERECHOS RESERVADOS
        </div>

        <nav className={styles.nav}>
          <ul>
            <li> <a href="#top"> Aviso Legal </a> </li>
            <li> <a href="#top"> Política de Privacidad </a> </li>
            <li> <a href="#top"> Política de Cookies </a> </li>
          </ul>
        </nav>
      </footer>

      </main>

    </>
  )
}


