import Head from 'next/head'
import Logo from '../images/Logo.png'
import Image from 'next/image'
import Aros from '../images/aros.jpg'
import Envelope from '../images/envelope.svg'
import styles2 from '@/styles/Login.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router';

const usersData = [
    {
        client_id: '1',
        email: 'juanperez@gmail.com',
        password: '12345',
        name: 'Juan',
        surname: 'Perez',
        birthdate: '1999-01-01',
        phone: '123456789',
        inscription_date: '2021-01-01',
        emergency_phone: '987654321',
        emergency_contact: 'Maria',
        rate_id: '1',
        available_classes: '12'
    },
    {
        client_id: '2',
        email: 'josehurtado@gmail.com',
        password: '54321',
        name: 'Jose',
        surname: 'Hurtado',
        birthdate: '1999-01-01',
        phone: '123456789',
        inscription_date: '2021-01-01',
        emergency_phone: '987654321',
        emergency_contact: 'Maria',
        rate_id: '1',
        available_classes: '12'
    },
    {
        client_id: '3',
        email: 'albalopez@gmail.com',
        password: 'abcdef',
        name: 'Alba',
        surname: 'Lopez',
        birthdate: '1999-01-01',
        phone: '123456789',
        inscription_date: '2021-01-01',
        emergency_phone: '987654321',
        emergency_contact: 'Maria',
        rate_id: '1',
        available_classes: '12'
    },
    {
        client_id: '4',
        email: 'raquelalvarez@gmail.com',
        password: 'fedcba',
        name: 'Raquel',
        surname: 'Alvarez',
        birthdate: '1999-01-01',
        phone: '123456789',
        inscription_date: '2021-01-01',
        emergency_phone: '987654321',
        emergency_contact: 'Maria',
        rate_id: '1',
        available_classes: '12'
    }
]

const initialFormData = {
    email: '',
    password: '',
}

export default function loginInfo(){
    const router = useRouter();

    const [formData, setFormData] = useState({
        email: '',
        password: ''
    });

    const handleEvent = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    }

    const handleSubmit = (e) => {
        e.preventDefault();
        const matchedUser = usersData.find(
            (user) =>
            user.email === formData.email && user.password === formData.password
        );
    
        if (matchedUser) {
            console.log('Login correcto');
            console.log(matchedUser);
            router.push(`/paginaUsuario?client_id=${matchedUser.client_id}`);
        } else {
            console.log('El usuario o la contraseña son incorrectos');
            alert('El usuario o la contraseña son incorrectos');
        }
    
        setFormData(initialFormData)
    }

    const isEmailValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email);
    const isPasswordValid = formData.password.trim() !== '';
  
    const isSubmitDisabled = !isEmailValid || !isPasswordValid;
    

    return (
        <>
            <Head>
                <title>Crear Usuario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles2.backgroundContainer}>
                <Image src={Aros} alt="manos" className={styles2.imagenFondo} />
                <div className={styles2.backgroundCanvas}>
                    <div className={styles2.propContainer}>
                        <Image src={Logo} alt="logo" className={styles2.logo} />
                        <form className={styles2.formContainer} onSubmit={handleSubmit}>
                            <input 
                                className={styles2.formInput}
                                name="email"
                                type="text"
                                placeholder='Email'
                                value={formData.email}
                                onChange={handleEvent}
                            />
                            <input
                                className={styles2.formInput}
                                name="password"
                                type="password"
                                placeholder='Contraseña'
                                value={formData.password}
                                onChange={handleEvent}
                            />
                            <br/>
                            <a href=''>¿Has olvidado tu contraseña?</a>
                            <br/>
                            <br/>
                            <button 
                                className={`${
                                    isSubmitDisabled ? styles2.disabledRoundButton : styles2.redRoundButton
                                  }`}
                                type="submit"
                                disabled={isSubmitDisabled}
                            >Iniciar Sesión
                            </button>
                        </form>
                    </div>
                </div>
            </div>


        </>
    )
}

