import Head from 'next/head'
import Logo from '../images/Logo.png'
import Image from 'next/image'
import Aros from '../images/aros.jpg'
import Envelope from '../images/envelope.svg'
import styles2 from '@/styles/Login.module.css'
import { useState } from 'react'

export default function CrearUsuarioInfo(){
    const initialFormData = {
        email: '',
        contrasena: '',
    }
    const [formData, setFormData] = useState({
        email: '',
        contrasena: ''
    });

    const handleEvent = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    }

    const handleSubmit = (e) => {
        e.preventDefault();
        console.log(formData);
        setFormData(initialFormData)
    }
    
    const passwordMatch = formData.contrasena === formData.contrasena2;

    return (
        <>
            <Head>
                <title>Crear Usuario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles2.backgroundContainer}>
                <Image src={Aros} alt="manos" className={styles2.imagenFondo} />
                <div className={styles2.backgroundCanvas}>
                    <div className={styles2.propContainer}>
                        <Image src={Logo} alt="logo" className={styles2.logo} />
                        <form className={styles2.formContainer} onSubmit={handleSubmit}>
                            <input 
                                className={styles2.formInput}
                                name="email"
                                type="text"
                                placeholder='Email'
                                value={formData.email}
                                onChange={handleEvent}
                            />
                            <input
                                className={styles2.formInput}
                                name="contrasena"
                                type="password"
                                placeholder='Contraseña'
                                value={formData.contrasena}
                                onChange={handleEvent}
                            />
                            <br/>
                            <a href=''>¿Has olvidado tu contraseña?</a>
                            <br/>
                            <br/>
                            <button 
                                className={styles2.redRoundButton}
                                type="submit"
                            >Iniciar Sesión
                            </button>
                        </form>
                    </div>
                </div>
            </div>


        </>
    )
}

