import Head from 'next/head'
import Logo from '../images/Logo.png'
import Image from 'next/image'
import Aros from '../images/aros.jpg'
import Pesas from '../images/55kg.jpg'
import Barra from '../images/barra.jpg'
import Envelope from '../images/envelope.svg'
import styles2 from '@/styles/PaginaUsuario.module.css'
import { useState } from 'react'

export default function CrearUsuarioInfo(){
    const initialFormData = {
        email: '',
        contrasena: '',
    }
    const [formData, setFormData] = useState({
        email: '',
        contrasena: ''
    });

    const handleEvent = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    }

    const handleSubmit = (e) => {
        e.preventDefault();
        console.log(formData);
        setFormData(initialFormData)
    }
    
    const passwordMatch = formData.contrasena === formData.contrasena2;

    return (
        <>
            <Head>
                <title>Crear Usuario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles2.backgroundContainer}>
                <Image src={Barra} alt="manos" className={styles2.imagenFondo} />
                <div className={styles2.backgroundCanvas}>
                </div>
            </div>


        </>
    )
}

